import userModel from "./user.js";
import tokenModel from "./token.js";
import logModel from "./log.js";
import ewardsModel from "./ewards.js";
import wooComerceModel from "./woo-commerce.js";
import ewardsKeyModel from "./ewards-key.js";
import Order from "./order.js";
import Coupon from "./woo-com-coupons.js";
import WooComCustomers from "./woo-com-customer.js";
import EWardsCart from "./ewards-cart.js";
import WoocomWebhook from "./woo-com-webhooks.js";

export const User = userModel;
export const Token = tokenModel;
export const Log = logModel;
export const EwardsMerchant = ewardsModel;
export const WooCommerce = wooComerceModel;
export const EwardsKey = ewardsKeyModel;
export const Orders = Order;
export const Coupons = Coupon;
export const Customer = WooComCustomers;
export const Cart = EWardsCart;
export const WoocomWebhooks = WoocomWebhook;
